import React, { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import BookmarkButton from './BookmarkButton'

export default function ChatMessage({ message, isUser, model, isStreaming, messageIndex, conversationId, userId }) {
  const [showLinkWarning, setShowLinkWarning] = useState(false)
  const [pendingLink, setPendingLink] = useState('')

  const handleLinkClick = (e) => {
    if (!isUser) {
      e.preventDefault()
      setPendingLink(e.currentTarget.href)
      setShowLinkWarning(true)
    }
  }

  const confirmOpenLink = () => {
    window.open(pendingLink, '_blank', 'noopener,noreferrer')
    setShowLinkWarning(false)
    setPendingLink('')
  }

  const cancelOpenLink = () => {
    setShowLinkWarning(false)
    setPendingLink('')
  }

  return (
    <>
      <div className={`flex ${isUser ? 'justify-end' : 'justify-start'} mb-4`}>
        <div
          className={`max-w-[80%] px-4 py-3 rounded-2xl ${
            isUser
              ? 'bg-[#2f2f2f] text-white'
              : 'text-gray-300'
          }`}
        >
          {!isUser && model && (
            <div className="text-xs font-semibold mb-2 opacity-70 flex items-center gap-1 whitespace-nowrap">
              {isStreaming ? (
                <>
                  <span className="inline-block w-2 h-2 bg-blue-400 rounded-full animate-pulse"></span>
                  <span>Using {model}</span>
                </>
              ) : (
                <>
                  <span className="inline-block w-2 h-2 bg-green-400 rounded-full"></span>
                  <span>Used {model}</span>
                </>
              )}
            </div>
          )}
          <div className="prose prose-sm prose-invert max-w-none break-words overflow-wrap-anywhere">
            {isUser ? (
              <p className="m-0 whitespace-pre-wrap">{message}</p>
            ) : (
                <>
                  <style>{`
                    .prose table {
                      width: 100%;
                      border-collapse: collapse;
                      margin: 1em 0;
                    }
                    .prose th {
                      background-color: #3f3f3f;
                      border: 1px solid #666;
                      padding: 0.75rem;
                      text-align: left;
                      font-weight: bold;
                    }
                    .prose td {
                      border: 1px solid #666;
                      padding: 0.75rem;
                    }
                    .prose tr:nth-child(even) {
                      background-color: #2a2a2a;
                    }
                  `}</style>
                  <ReactMarkdown 
                    remarkPlugins={[remarkGfm]}
                    components={{
                      a: ({node, ...props}) => (
                        <a {...props} onClick={handleLinkClick} className="text-blue-400 hover:underline cursor-pointer" />
                      )
                    }}
                  >
                    {message}
                  </ReactMarkdown>
                </>
              )}
          </div>
          
          {/* Action Buttons for AI messages */}
          {!isUser && !isStreaming && (
            <div className="flex items-center gap-2 mt-2 ml-2">
              <BookmarkButton
                messageText={message}
                messageIndex={messageIndex}
                conversationId={conversationId}
                userId={userId}
                isBookmarked={false}
              />
              <button
                onClick={() => navigator.clipboard.writeText(message)}
                className="p-1.5 rounded-lg text-gray-400 hover:text-gray-300 transition"
                title="Copy to clipboard"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"/>
                  <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"/>
                </svg>
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Warning Modal */}
      {showLinkWarning && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" onClick={cancelOpenLink}>
          <div className="bg-[#2f2f2f] rounded-lg p-6 max-w-md mx-4 border border-[#3f3f3f]" onClick={(e) => e.stopPropagation()}>
            <h3 className="text-lg font-semibold text-white mb-3">⚠️ AI-Generated Link Warning</h3>
            <p className="text-gray-300 mb-4">
              This link was generated by AI and may not be accurate or safe. Please verify the destination before proceeding.
            </p>
            <p className="text-sm text-gray-400 mb-4 break-all">
              <strong>URL:</strong> {pendingLink}
            </p>
            <div className="flex gap-3 justify-end">
              <button
                onClick={cancelOpenLink}
                className="px-4 py-2 bg-[#3f3f3f] hover:bg-[#4f4f4f] text-white rounded-lg transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={confirmOpenLink}
                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors"
              >
                Open Link
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}



